### ISSUE TITLE
updating shares

### ISSUE THREAD

**Issue by moscicki** [cs3org/OCM-API#36]
There is no way of updating shares — is this intentional?

**Comment by dvh** [comment]
@moscicki it is indeed intentional as the create call is a 'fire and forget' call. The receiving party might have removed the incoming share without notifying the sending party. This could be fixed by returning a `404 Not found` or `410 Gone` but then I wouldn't see the specific use of an update call. Updating the file (permissions) should be part of the specific protocol i.m.h.o. Updating the share itself could be intended to change the receiving user, name, description or the protocol itself, but once it already has been processed by the receiving party changing the user, name or description doesn't have any impact at all and changing the protocol would make things extremely complex.

I could add a `PUT` call the `/shares/{id}` quite easily, but I doubt if it offers a lot of added value.

**Comment by michielbdejong** [comment]
Related to #107.
Closing as a question that was answered.
